server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/eating_simulator?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: test_123
    driver-class-name: com.mysql.jdbc.Driver
